# Notebook for Component 1

## Calculate the distance from epicenter

In [10]:
#install haversine package
!pip install haversine

Requirement already satisfied: haversine in /Users/kingminglai/anaconda/lib/python3.6/site-packages

In [12]:
import pandas as pd

In [31]:
location = pd.read_table("location.txt", header=None)

In [59]:
location.columns = ['x', 'y', 'epi_x', 'epi_y']

In [25]:
# epicenter of Tohoku earthquake
# https://en.wikipedia.org/wiki/2011_T≈çhoku_earthquake_and_tsunami
# epi = (142.369, 38.322)

In [62]:
location['epi_x'] = 142.369
location['epi_y'] = 38.322

In [63]:
location.head()

         x       y    epi_x   epi_y
0  -98.683  27.065  142.369  38.322
1  -98.102  26.938  142.369  38.322
2  -98.068  26.463  142.369  38.322
3 -117.110  32.889  142.369  38.322
4 -107.790  32.532  142.369  38.322

In [24]:
from haversine import haversine

In [40]:
distance = haversine(location.iloc[0][:2], epi)

In [76]:
for i in (range(len(location))):
    location['distance'].iloc[i] = haversine(location.iloc[i][:2], location.iloc[i][2:4])

In [78]:
location.head()

          x       y    epi_x   epi_y      distance
433 -95.623  33.198  142.369  38.322  13569.000735
434 -94.985  33.260  142.369  38.322  13639.643991
435 -94.182  33.242  142.369  38.322  13728.634830
436 -93.400  33.258  142.369  38.322  13815.269749
437 -92.803  33.258  142.369  38.322  13881.413634

In [79]:
location.tail()

          x       y    epi_x   epi_y      distance
433 -95.623  33.198  142.369  38.322  13569.000735
434 -94.985  33.260  142.369  38.322  13639.643991
435 -94.182  33.242  142.369  38.322  13728.634830
436 -93.400  33.258  142.369  38.322  13815.269749
437 -92.803  33.258  142.369  38.322  13881.413634

In [83]:
location = location.sort_values('distance')

In [84]:
location

           x       y    epi_x   epi_y      distance
211 -123.930  43.161  142.369  38.322  10429.135668
193 -123.850  44.106  142.369  38.322  10442.312210
228 -123.670  42.696  142.369  38.322  10456.153642
244 -123.600  42.158  142.369  38.322  10462.041390
194 -123.350  43.697  142.369  38.322  10495.800538
165 -123.260  45.212  142.369  38.322  10513.620991
257 -122.850  41.392  142.369  38.322  10543.108065
151 -123.010  46.083  142.369  38.322  10546.640003
288 -122.790  40.177  142.369  38.322  10547.275145
122 -123.090  47.535  142.369  38.322  10548.134779
272 -122.700  40.974  142.369  38.322  10558.775872
179 -122.740  44.523  142.369  38.322  10567.423785
123 -122.770  47.179  142.369  38.322  10580.752129
137 -122.570  46.557  142.369  38.322  10598.422893
83  -122.710  48.720  142.369  38.322  10599.689564
195 -122.410  43.794  142.369  38.322  10600.468260
245 -122.300  42.218  142.369  38.322  10606.581560
212 -122.110  43.240  142.369  38.322  10631.371214
258 -121.840  41.783  142.369  38.322  10656.353087
289 -121.800  40.295  142.369  38.322  10657.505467
94  -122.100  48.264  142.369  38.322  10663.027245
229 -121.750  42.625  142.369  38.322  10669.004860
152 -121.460  45.885  142.369  38.322  10716.773126
196 -121.340  44.339  142.369  38.322  10721.617704
166 -121.320  45.242  142.369  38.322  10728.520329
213 -121.230  43.285  142.369  38.322  10729.172500
107 -120.890  47.923  142.369  38.322  10793.656329
3   -117.110  32.889  142.369  38.322  11187.932703
376 -116.450  33.606  142.369  38.322  11258.570606
332 -115.590  38.349  142.369  38.322  11346.441757
..       ...     ...      ...     ...           ...
47   -92.431  30.712  142.369  38.322  13923.911852
136  -92.426  47.158  142.369  38.322  13925.263395
150  -92.400  46.566  142.369  38.322  13927.725201
210  -92.331  44.041  142.369  38.322  13933.975955
36   -92.325  31.375  142.369  38.322  13935.233065
345  -92.268  38.291  142.369  38.322  13939.729625
119  -92.185  47.728  142.369  38.322  13952.134125
25   -92.152  32.062  142.369  38.322  13954.015606
331  -92.075  38.995  142.369  38.322  13961.205701
317  -92.048  39.530  142.369  38.322  13964.241748
14   -91.946  32.549  142.369  38.322  13976.604276
303  -91.874  40.121  142.369  38.322  13983.640608
61   -91.856  30.086  142.369  38.322  13987.619484
48   -91.781  30.764  142.369  38.322  13995.562452
37   -91.617  31.284  142.369  38.322  14013.443872
26   -91.483  31.880  142.369  38.322  14028.038720
15   -91.404  32.703  142.369  38.322  14036.538420
120  -91.273  47.717  142.369  38.322  14052.235777
62   -91.161  30.110  142.369  38.322  14064.126006
49   -90.746  30.715  142.369  38.322  14109.691108
63   -90.489  30.044  142.369  38.322  14138.108211
50   -90.338  30.730  142.369  38.322  14154.663776
121  -90.129  47.817  142.369  38.322  14177.771714
359  -87.097  40.379  142.369  38.322  14514.501902
375  -83.590  31.439  142.369  38.322  14899.033983
242  -81.333  35.142  142.369  38.322  15153.951828
286  -79.989  40.962  142.369  38.322  15303.710591
269  -79.665  41.508  142.369  38.322  15339.030102
304  -78.566  40.268  142.369  38.322  15462.442118
287  -75.770  40.917  142.369  38.322  15772.164436

[438 rows x 5 columns]